project:
  type: website
  output-dir: ../docs

website:
  title: "Kishan's home on the Internet"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/KishanPipariya
      - icon: twitter
        href: https://twitter.com/intelkishan
format:
  html:
    theme: cosmo
    css: styles.css



